# Integration tests for keras3 / kerasnip model layers
# These tests are skipped when required packages are not installed.
# Auto-generated by _split_tests.py — do not edit the split boundary manually.

# Integration tests for keras / keras3 / kerasnip MLP engines
# These tests are skipped when the relevant packages are not installed.

# ── keras3 (modern API, Sequential) ──────────────────────────────────────────

test_that("mlp() keras3 Sequential works with regression", {
  skip_if_no_keras3()

  # Build a simple keras3 Sequential MLP directly (not via parsnip)
  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(4L, activation = "relu", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  # Fit on tiny data
  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 2L, verbose = 0L)

  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = paste0("x", 1:3)
  )
  expect_true(is.character(orb_obj))
  expect_named(orb_obj, ".pred", ignore.order = TRUE)
})

test_that("mlp() keras3 Sequential works with binary classification", {
  skip_if_no_keras3()

  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(4L, activation = "relu", input_shape = list(3L)),
    k$layers$Dense(1L, activation = "sigmoid")
  ))
  model$compile(optimizer = "adam", loss = "binary_crossentropy")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- as.integer(rnorm(10) > 0)
  model$fit(x_mat, y_vec, epochs = 2L, verbose = 0L)

  orb_obj <- orbital(
    model,
    mode = "classification",
    type = "class",
    lvl = c("0", "1"),
    feature_names = paste0("x", 1:3)
  )
  expect_true(is.character(orb_obj))
  expect_true(".pred_class" %in% names(orb_obj))
})

test_that("mlp() keras3 Sequential works with multiclass (softmax)", {
  skip_if_no_keras3()

  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(8L, activation = "relu", input_shape = list(4L)),
    k$layers$Dense(3L, activation = "softmax")
  ))
  model$compile(optimizer = "adam", loss = "sparse_categorical_crossentropy")

  set.seed(42)
  x_mat <- matrix(rnorm(40), nrow = 10, ncol = 4)
  y_vec <- sample(0:2, 10, replace = TRUE)
  model$fit(x_mat, y_vec, epochs = 2L, verbose = 0L)

  orb_obj <- orbital(
    model,
    mode = "classification",
    type = "class",
    lvl = c("0", "1", "2"),
    feature_names = paste0("x", 1:4)
  )
  expect_true(is.character(orb_obj))
})

# ── swish and mish activations ────────────────────────────────────────────────

test_that("keras3 model with swish activation is translatable", {
  skip_if_no_keras3()

  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(4L, activation = "swish", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  model$fit(x_mat, rnorm(10), epochs = 2L, verbose = 0L)

  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = paste0("x", 1:3)
  )
  # swish expressions should contain the characteristic "(1 / (1 + exp(-" pattern
  hidden_exprs <- orb_obj[grepl("orbital_mlp", names(orb_obj))]
  expect_true(any(grepl("exp", hidden_exprs)))
})

# ── kerasnip (skip if not installed) ─────────────────────────────────────────

test_that("mlp() kerasnip engine works with regression", {
  skip_if_not_installed("kerasnip")
  skip_if_not_installed("parsnip")
  skip_if_not(
    tryCatch(
      {
        parsnip::mlp(engine = "kerasnip")
        TRUE
      },
      error = function(e) FALSE
    ),
    "kerasnip engine not registered with parsnip"
  )

  spec <- parsnip::mlp(hidden_units = 3, epochs = 5, engine = "kerasnip")
  spec <- parsnip::set_mode(spec, "regression")

  set.seed(1)
  fit <- parsnip::fit(spec, mpg ~ disp + wt + hp, mtcars)

  orb_obj <- orbital(fit)
  preds <- predict(orb_obj, mtcars)

  expect_named(preds, ".pred")
  expect_type(preds$.pred, "double")
})

test_that("mlp() kerasnip engine works with binary classification", {
  skip_if_not_installed("kerasnip")
  skip_if_not_installed("parsnip")
  skip_if_not(
    tryCatch(
      {
        parsnip::mlp(engine = "kerasnip")
        TRUE
      },
      error = function(e) FALSE
    ),
    "kerasnip engine not registered with parsnip"
  )

  mtcars$vs <- factor(mtcars$vs)
  spec <- parsnip::mlp(hidden_units = 3, epochs = 5, engine = "kerasnip")
  spec <- parsnip::set_mode(spec, "classification")

  set.seed(1)
  fit <- parsnip::fit(spec, vs ~ disp + wt + hp, mtcars)

  orb_obj <- orbital(fit, type = "class")
  preds <- predict(orb_obj, mtcars)

  expect_named(preds, ".pred_class")
  expect_type(preds$.pred_class, "character")
})

# ── activations: ELU, GELU, hard_swish ───────────────────────────────────────

test_that("keras3 Sequential model with ELU activation translates correctly", {
  skip_if_no_keras3()

  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(4L, activation = "elu", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  model$fit(x_mat, rnorm(10), epochs = 2L, verbose = 0L)

  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = paste0("x", 1:3)
  )
  expect_true(is.character(orb_obj))
  hidden_exprs <- orb_obj[grepl("orbital_mlp", names(orb_obj))]
  # ELU expression must contain exp()
  expect_true(any(grepl("exp\\(", hidden_exprs)))
})

test_that("keras3 Sequential model with GELU activation translates correctly", {
  skip_if_no_keras3()

  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(4L, activation = "gelu", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  model$fit(x_mat, rnorm(10), epochs = 2L, verbose = 0L)

  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = paste0("x", 1:3)
  )
  expect_true(is.character(orb_obj))
  hidden_exprs <- orb_obj[grepl("orbital_mlp", names(orb_obj))]
  # After the GELU fix the expression uses the A&S erf approximation
  # (exact form); the 1/sqrt(2) constant is the distinguishing token.
  expect_true(any(grepl("0.7071067811865476", hidden_exprs)))
})

test_that("keras3 Sequential model with hard_sigmoid activation translates correctly", {
  skip_if_no_keras3()

  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(4L, activation = "hard_sigmoid", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  model$fit(x_mat, rnorm(10), epochs = 2L, verbose = 0L)

  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = paste0("x", 1:3)
  )
  expect_true(is.character(orb_obj))
  hidden_exprs <- orb_obj[grepl("orbital_mlp", names(orb_obj))]
  expect_true(any(grepl("0\\.2", hidden_exprs)))
})

# ── multiclass probability output (R #19) ────────────────────────────────────

test_that("keras3 Sequential multiclass model outputs class probabilities", {
  skip_if_no_keras3()

  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(8L, activation = "relu", input_shape = list(4L)),
    k$layers$Dense(3L, activation = "softmax")
  ))
  model$compile(optimizer = "adam", loss = "sparse_categorical_crossentropy")

  set.seed(42)
  x_mat <- matrix(rnorm(40), nrow = 10, ncol = 4)
  y_vec <- sample(0:2, 10, replace = TRUE)
  model$fit(x_mat, y_vec, epochs = 2L, verbose = 0L)

  orb_obj <- orbital(
    model,
    mode = "classification",
    type = "prob",
    lvl = c("cat_a", "cat_b", "cat_c"),
    feature_names = paste0("x", 1:4)
  )
  expect_true(is.character(orb_obj))
  expect_true(".pred_cat_a" %in% names(orb_obj))
  expect_true(".pred_cat_b" %in% names(orb_obj))
  expect_true(".pred_cat_c" %in% names(orb_obj))
})

test_that("keras3 PReLU predictions match keras3 predict (regression)", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(3L))
  x <- k$layers$Dense(6L)(inp)
  x <- k$layers$PReLU()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:3)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

test_that("keras3 Concatenate predictions match keras3 predict (regression)", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(4L))
  branch_a <- k$layers$Dense(3L, activation = "relu")(inp)
  branch_b <- k$layers$Dense(3L, activation = "tanh")(inp)
  merged <- k$layers$Concatenate()(list(branch_a, branch_b))
  out <- k$layers$Dense(1L)(merged)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(40), nrow = 10, ncol = 4)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:4)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

test_that("keras3 ELU activation predictions match keras3 predict (regression)", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(6L, activation = "elu", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:3)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

test_that("keras3 GELU activation predictions match keras3 predict (regression)", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(6L, activation = "gelu", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:3)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

# ── activations: selu, mish, softplus, softsign, leaky_relu (R audit rec #1) ─

test_that("keras3 Sequential model with SELU activation predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(6L, activation = "selu", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:3)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  hidden_exprs <- orb_obj[grepl("orbital_mlp", names(orb_obj))]
  # Every SELU expression must contain the SELU scale constant
  expect_true(any(grepl("1.0507009873554805", hidden_exprs)))
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

test_that("keras3 Sequential model with Mish activation predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(6L, activation = "mish", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:3)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  hidden_exprs <- orb_obj[grepl("orbital_mlp", names(orb_obj))]
  # Mish uses tanh(log(1 + exp(x))) — both tanh and log must appear
  expect_true(any(grepl("tanh", hidden_exprs)))
  expect_true(any(grepl("log", hidden_exprs)))
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

test_that("keras3 Sequential model with Softplus activation predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(6L, activation = "softplus", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:3)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  hidden_exprs <- orb_obj[grepl("orbital_mlp", names(orb_obj))]
  expect_true(any(grepl("log\\(1 \\+ exp", hidden_exprs)))
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

test_that("keras3 Sequential model with Softsign activation predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(6L, activation = "softsign", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:3)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  hidden_exprs <- orb_obj[grepl("orbital_mlp", names(orb_obj))]
  expect_true(any(grepl("abs", hidden_exprs)))
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

# ── swish / hard_swish activation accuracy (audit rec #4) ────────────────────

test_that("keras3 Sequential model with swish activation predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  model <- k$Sequential(list(
    k$layers$Dense(6L, activation = "swish", input_shape = list(3L)),
    k$layers$Dense(1L)
  ))
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(30), nrow = 10, ncol = 3)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:3)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

# ── multi-output model accuracy (audit rec #8) ───────────────────────────────

test_that("keras3 Functional two-output model predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(4L))
  x <- k$layers$Dense(8L, activation = "relu")(inp)
  out1 <- k$layers$Dense(1L, name = "output_1")(x)
  out2 <- k$layers$Dense(1L, name = "output_2")(x)
  model <- k$Model(inputs = inp, outputs = list(out1, out2))
  model$compile(optimizer = "adam", loss = list("mse", "mse"))

  set.seed(42)
  x_mat <- matrix(rnorm(40), nrow = 10, ncol = 4)
  y1 <- rnorm(10)
  y2 <- rnorm(10)
  model$fit(x_mat, list(y1, y2), epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:4)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = feature_names
  )
  preds_orb <- predict(orb_obj, df)
  preds_keras <- model$predict(x_mat, verbose = 0L)
  # keras returns a list of two arrays for two outputs
  k_out1 <- as.numeric(preds_keras[[1L]])
  k_out2 <- as.numeric(preds_keras[[2L]])
  expect_equal(preds_orb$.pred_1, k_out1, tolerance = 1e-5)
  expect_equal(preds_orb$.pred_2, k_out2, tolerance = 1e-5)
})

# ── E2: coverage gap tests ────────────────────────────────────────────────────

test_that("keras3 ReLU(negative_slope=0.3) predictions match keras3 predict", {
  .keras_skip()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(4L))
  x <- k$layers$Dense(6L)(inp)
  x <- k$layers$ReLU(negative_slope = 0.3)(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(40), nrow = 10, ncol = 4)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", 1:4)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

# ── multi-output Functional API: classification (R#32) ────────────────────────

test_that("keras3 Functional binary classifier predictions numerically match keras3 predict", {
  .keras_skip()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(4L))
  x <- k$layers$Dense(8L, activation = "relu")(inp)
  out <- k$layers$Dense(1L, activation = "sigmoid")(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "binary_crossentropy")

  set.seed(42)
  x_mat <- matrix(rnorm(40), nrow = 10, ncol = 4)
  y_vec <- as.integer(rnorm(10) > 0)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:4)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(
    model,
    mode = "classification",
    type = "prob",
    lvl = c("0", "1"),
    feature_names = feature_names
  )
  preds_orb <- predict(orb_obj, df)
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  # keras returns p(class=1); orbital .pred_1 should match
  expect_equal(preds_orb$.pred_1, preds_keras, tolerance = 1e-5)
  # probabilities sum to 1
  expect_equal(
    preds_orb$.pred_0 + preds_orb$.pred_1,
    rep(1, 10),
    tolerance = 1e-6
  )
})

# ── EinsumDense ───────────────────────────────────────────────────────────────
test_that("keras3 EinsumDense (ab,bc->ac) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(4L))
  x <- k$layers$Dense(8L, activation = "relu")(inp)
  x <- k$layers$EinsumDense("ab,bc->ac", output_shape = 6L, bias_axes = "c")(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(40), nrow = 10, ncol = 4)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:4)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_mat, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})

# ── EinsumDense with non-default activation alpha ─────────────────────────────

test_that("keras3 EinsumDense with LeakyReLU(alpha=0.2) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(4L))
  x <- k$layers$Dense(8L, activation = "relu")(inp)
  x <- k$layers$EinsumDense(
    "ab,bc->ac",
    output_shape = 6L,
    bias_axes = "c",
    activation = k$layers$LeakyReLU(negative_slope = 0.2)
  )(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_mat <- matrix(rnorm(40), nrow = 10, ncol = 4)
  y_vec <- rnorm(10)
  model$fit(x_mat, y_vec, epochs = 5L, verbose = 0L)

  feature_names <- paste0("x", 1:4)
  df <- as.data.frame(x_mat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  expect_equal(
    predict(orb_obj, df)$.pred,
    as.numeric(model$predict(x_mat, verbose = 0L)),
    tolerance = 1e-5
  )
})

# ── Wave 1A regression: Sequential Dense(use_bias=FALSE) weight-counting fix ──

test_that("Sequential Dense(use_bias=FALSE) + Dense produces correct predictions (Wave 1A regression)", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")

  model <- k$Sequential(list(
    k$Input(shape = list(3L)),
    k$layers$Dense(units = 8L, use_bias = FALSE, activation = "relu"),
    k$layers$Dense(units = 1L)
  ))

  # Wave 1A fix: per-layer weight counting instead of length(all_weights)/2.
  # Layer 0 (use_bias=FALSE) has 1 weight; layer 1 has 2 weights.
  set.seed(42)
  w1 <- matrix(rnorm(3L * 8L), nrow = 3L, ncol = 8L) # kernel (3 × 8)
  w2 <- matrix(rnorm(8L * 1L), nrow = 8L, ncol = 1L) # kernel (8 × 1)
  b2 <- array(rnorm(1L), dim = 1L) # bias  (1,)
  model$set_weights(list(w1, w2, b2))

  feature_names <- c("a", "b", "c")
  df <- data.frame(a = c(1, 2, 3), b = c(-1, 0, 1), c = c(0.5, -0.5, 2))

  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(
    model$predict(as.matrix(df[, feature_names]), verbose = 0L)
  )
  expect_equal(preds_orb, preds_keras, tolerance = 1e-5)
})
