# Integration tests for keras3 / kerasnip model layers
# These tests are skipped when required packages are not installed.
# Auto-generated by _split_tests.py — do not edit the split boundary manually.

# ── B4: LSTM, GRU, Conv1D, RMSNormalization coverage tests ───────────────────

test_that("keras3 LSTM (return_sequences=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$LSTM(H, return_sequences = FALSE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 LSTM (return_sequences=TRUE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$LSTM(H, return_sequences = TRUE)(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 GRU (return_sequences=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$GRU(H, return_sequences = FALSE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 GRU (return_sequences=TRUE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$GRU(H, return_sequences = TRUE)(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, concat) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = FALSE),
    merge_mode = "concat"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(GRU, concat) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$GRU(H, return_sequences = FALSE),
    merge_mode = "concat"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, sum) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = FALSE),
    merge_mode = "sum"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, ave) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = FALSE),
    merge_mode = "ave"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, return_sequences=TRUE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 2L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = TRUE),
    merge_mode = "concat"
  )(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 SimpleRNN (return_sequences=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$SimpleRNN(H, return_sequences = FALSE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 SimpleRNN (return_sequences=TRUE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$SimpleRNN(H, return_sequences = TRUE)(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 GRU (reset_after=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$GRU(H, return_sequences = FALSE, reset_after = FALSE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, mul) predictions match keras3 predict", {
  .keras_skip()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = FALSE),
    merge_mode = "mul"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  expect_equal(
    predict(orb_obj, df)$.pred,
    as.numeric(model$predict(x_3d, verbose = 0L)),
    tolerance = 1e-4
  )
})

test_that("keras3 stateful LSTM raises cli_abort", {
  .keras_skip()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(3L, 2L))
  x <- k$layers$LSTM(4L, stateful = TRUE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  feature_names <- paste0("x", 1:6)
  expect_error(
    orbital(model, mode = "regression", feature_names = feature_names),
    "stateful"
  )
})

test_that("keras3 stateful GRU raises cli_abort", {
  .keras_skip()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(3L, 2L))
  x <- k$layers$GRU(4L, stateful = TRUE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  feature_names <- paste0("x", 1:6)
  expect_error(
    orbital(model, mode = "regression", feature_names = feature_names),
    "stateful"
  )
})

# ── ConvLSTM1D ────────────────────────────────────────────────────────────────
test_that("keras3 ConvLSTM1D (return_sequences=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  S_len <- 1L
  C_in <- 2L
  F_filt <- 4L
  inp <- k$Input(shape = list(T_len, S_len, C_in))
  x <- k$layers$ConvLSTM1D(
    filters = F_filt,
    kernel_size = 3L,
    padding = "same",
    return_sequences = FALSE
  )(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * S_len * C_in),
    nrow = n_row,
    ncol = T_len * S_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_4d <- array(x_flat, dim = c(n_row, T_len, S_len, C_in))
  model$fit(x_4d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * S_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_4d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

# ── ConvLSTM1D error paths ────────────────────────────────────────────────────

test_that("keras3 ConvLSTM1D stateful=TRUE raises cli_abort", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  S_len <- 1L
  C_in <- 2L
  F_filt <- 4L
  inp <- k$Input(shape = list(T_len, S_len, C_in))
  x <- k$layers$ConvLSTM1D(
    filters = F_filt,
    kernel_size = 3L,
    padding = "same",
    return_sequences = FALSE,
    stateful = TRUE
  )(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)

  feature_names <- paste0("x", seq_len(T_len * S_len * C_in))
  expect_error(
    orbital(model, mode = "regression", feature_names = feature_names),
    "stateful"
  )
})

# ── Bidirectional merge_mode=None ─────────────────────────────────────────────

test_that("keras3 Bidirectional(LSTM, merge_mode=None) falls back to concat", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  units <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(units, return_sequences = FALSE),
    merge_mode = reticulate::r_to_py(NULL)
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 2L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  # merge_mode=None falls back to concat silently
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  expect_s3_class(orb_obj, "orbital_class")
})

# ── .detect_masking_upstream unit tests (R-G: masking detection) ─────────────

test_that(".detect_masking_upstream returns TRUE when direct parent is a masking layer", {
  topo <- list(
    lstm_1 = "masking",
    masking = "embedding_1",
    embedding_1 = character(0L)
  )
  expect_true(orbital:::.detect_masking_upstream("lstm_1", topo))
})

test_that(".detect_masking_upstream returns TRUE when masking layer is two hops upstream", {
  topo <- list(
    lstm_1 = "dense_1",
    dense_1 = "masking",
    masking = "input_1",
    input_1 = character(0L)
  )
  expect_true(orbital:::.detect_masking_upstream("lstm_1", topo))
})

test_that(".detect_masking_upstream returns FALSE when no masking layer is upstream", {
  topo <- list(
    lstm_1 = "embedding_1",
    embedding_1 = "input_1",
    input_1 = character(0L)
  )
  expect_false(orbital:::.detect_masking_upstream("lstm_1", topo))
})

test_that(".detect_masking_upstream returns FALSE for an empty topo_map entry", {
  topo <- list(lstm_1 = character(0L))
  expect_false(orbital:::.detect_masking_upstream("lstm_1", topo))
})

test_that(".detect_masking_upstream returns FALSE for an unknown layer name", {
  topo <- list(some_layer = "input_1", input_1 = character(0L))
  expect_false(orbital:::.detect_masking_upstream("nonexistent_layer", topo))
})

test_that(".detect_masking_upstream is case-insensitive for masking layer prefix", {
  topo <- list(lstm_1 = "Masking_layer", Masking_layer = character(0L))
  expect_true(orbital:::.detect_masking_upstream("lstm_1", topo))
})

# ── Wave 1A regression: Bidirectional(LSTM) 2-row bias colSums fix ────────────

test_that("Bidirectional(LSTM, concat) with explicit 2-row bias matrices gives correct predictions (Wave 1A regression)", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 4L
  n_row <- 5L

  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = FALSE),
    merge_mode = "concat"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  # Fit briefly to allocate weight tensors with keras-assigned shapes
  set.seed(42)
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 1L, verbose = 0L)

  # Verify that keras3 Bidirectional LSTM stores bias as 2-row matrix
  curr_wts <- model$get_weights()
  skip_if(
    !is.matrix(curr_wts[[3L]]) || nrow(curr_wts[[3L]]) != 2L,
    "Keras version does not produce 2-row LSTM bias; skipping Wave 1A 2-row bias regression test"
  )

  # Replace bias entries with controlled (2, 4H) values to exercise colSums fix
  set.seed(99)
  curr_wts[[3L]] <- matrix(rnorm(2L * 4L * H), nrow = 2L, ncol = 4L * H)
  curr_wts[[6L]] <- matrix(rnorm(2L * 4L * H), nrow = 2L, ncol = 4L * H)
  model$set_weights(curr_wts)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names

  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  expect_equal(
    predict(orb_obj, df)$.pred,
    as.numeric(model$predict(x_3d, verbose = 0L)),
    tolerance = 1e-4
  )
})

# ── C5 regression: GRU reset_after=FALSE no NA; go_backwards ordering ─────────

test_that("keras3 GRU (reset_after=FALSE) orbital expressions contain no NA values", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 2L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$GRU(H, return_sequences = FALSE, reset_after = FALSE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 1L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  exprs <- unclass(orb_obj)

  # Regression guard: the C5 bug caused NA to appear in the h-tilde expressions
  expect_false(any(grepl("\\bNA\\b", exprs)))
  expect_true(all(is.character(exprs)))
})

test_that("keras3 LSTM (go_backwards=TRUE) produces different orbital expressions than go_backwards=FALSE", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 2L

  make_lstm_model <- function(go_bwd) {
    inp <- k$Input(shape = list(T_len, C_in))
    x <- k$layers$LSTM(H, return_sequences = FALSE, go_backwards = go_bwd)(inp)
    out <- k$layers$Dense(1L)(x)
    mdl <- k$Model(inputs = inp, outputs = out)
    mdl$compile(optimizer = "adam", loss = "mse")
    mdl
  }

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))

  model_fwd <- make_lstm_model(FALSE)
  model_bwd <- make_lstm_model(TRUE)
  # Fit forward model then copy identical weights to backward model so that any
  # expression difference is purely structural (loop order), not numerical.
  model_fwd$fit(x_3d, rnorm(n_row), epochs = 1L, verbose = 0L)
  model_bwd$set_weights(model_fwd$get_weights())

  feature_names <- paste0("x", seq_len(T_len * C_in))
  orb_fwd <- orbital(
    model_fwd,
    mode = "regression",
    feature_names = feature_names
  )
  orb_bwd <- orbital(
    model_bwd,
    mode = "regression",
    feature_names = feature_names
  )

  # Regression guard: go_backwards changes the time-step traversal order, so
  # the symbolic expression chain must differ between the two directions.
  expect_false(identical(unclass(orb_fwd), unclass(orb_bwd)))
})

test_that("keras3 GRU (go_backwards=TRUE) produces different orbital expressions than go_backwards=FALSE", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 2L

  make_gru_model <- function(go_bwd) {
    inp <- k$Input(shape = list(T_len, C_in))
    x <- k$layers$GRU(H, return_sequences = FALSE, go_backwards = go_bwd)(inp)
    out <- k$layers$Dense(1L)(x)
    mdl <- k$Model(inputs = inp, outputs = out)
    mdl$compile(optimizer = "adam", loss = "mse")
    mdl
  }

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))

  model_fwd <- make_gru_model(FALSE)
  model_bwd <- make_gru_model(TRUE)
  model_fwd$fit(x_3d, rnorm(n_row), epochs = 1L, verbose = 0L)
  model_bwd$set_weights(model_fwd$get_weights())

  feature_names <- paste0("x", seq_len(T_len * C_in))
  orb_fwd <- orbital(
    model_fwd,
    mode = "regression",
    feature_names = feature_names
  )
  orb_bwd <- orbital(
    model_bwd,
    mode = "regression",
    feature_names = feature_names
  )

  # Regression guard: same as LSTM — loop order differs, so expressions differ.
  expect_false(identical(unclass(orb_fwd), unclass(orb_bwd)))
})
