# Integration tests for keras3 / kerasnip model layers
# These tests are skipped when required packages are not installed.
# Auto-generated by _split_tests.py — do not edit the split boundary manually.

test_that("keras3 MultiHeadAttention (self-attention) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 8L
  num_heads <- 2L
  key_dim <- 4L

  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$MultiHeadAttention(
    num_heads = num_heads,
    key_dim = key_dim
  )(inp, inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

# ── Attention ─────────────────────────────────────────────────────────────────

test_that("keras3 Attention (self-attention) predictions match keras3 predict", {
  .keras_skip()
  k <- reticulate::import("keras")
  T_len <- 4L
  C_in <- 3L

  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Attention(use_scale = FALSE)(list(inp, inp))
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  expect_equal(
    predict(orb_obj, df)$.pred,
    as.numeric(model$predict(x_3d, verbose = 0L)),
    tolerance = 1e-4
  )
})

# ── AdditiveAttention layer ───────────────────────────────────────────────────

test_that("keras3 AdditiveAttention (Bahdanau) predictions match keras3 predict", {
  .keras_skip()
  k <- reticulate::import("keras")
  T_len <- 2L
  C_in <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  q <- k$layers$Dense(C_in)(inp)
  v <- k$layers$Dense(C_in)(inp)
  x <- k$layers$AdditiveAttention(use_scale = FALSE)(list(q, v))
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  x_arr <- array(rnorm(10 * T_len * C_in), dim = c(10L, T_len, C_in))
  model$fit(x_arr, rnorm(10), epochs = 2L, verbose = 0L)

  x_flat <- matrix(x_arr, nrow = 10, ncol = T_len * C_in)
  df <- as.data.frame(x_flat)
  names(df) <- paste0("x", seq_len(T_len * C_in))
  orb_obj <- orbital(
    model,
    mode = "regression",
    feature_names = names(df)
  )
  expect_equal(
    predict(orb_obj, df)$.pred,
    as.numeric(model$predict(x_arr, verbose = 0L)),
    tolerance = 1e-4
  )
})
test_that("keras3 GroupedQueryAttention (GQA) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 8L
  num_heads <- 4L
  num_query_groups <- 2L
  head_dim <- 4L

  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$GroupedQueryAttention(
    head_dim = head_dim,
    num_heads = num_heads,
    num_query_groups = num_query_groups
  )(inp, inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

# ── MHA causal-mask warning ───────────────────────────────────────────────────

test_that("keras3 MultiHeadAttention without causal mask translates successfully (Wave 1A: no unconditional warning)", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 8L
  num_heads <- 2L
  key_dim <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$MultiHeadAttention(
    num_heads = num_heads,
    key_dim = key_dim
  )(inp, inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 2L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  # Wave 1A: unconditional use_causal_mask warning was removed.
  # use_causal_mask=FALSE (default) should translate successfully with no error.
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  expect_s3_class(orb_obj, "orbital_class")
})

# ── MHA kernel layout ambiguity error (Issue 2) ───────────────────────────────

test_that("keras3 MHA errors with orbital_mha_kernel_ambiguous when num_heads == key_dim", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 8L
  # num_heads == key_dim now raises an error in .make_proj_at()
  num_heads <- 4L
  key_dim <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$MultiHeadAttention(
    num_heads = num_heads,
    key_dim = key_dim
  )(inp, inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 2L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  expect_error(
    orbital(model, mode = "regression", feature_names = feature_names),
    class = "orbital_mha_kernel_ambiguous"
  )
})

# ── Wave 1A regression (superseded by R-03): use_causal_mask=TRUE is now
#     supported for static sequence lengths. See the R-03 test below for the
#     positive-path coverage that replaces this abort-expectation test.

# ---------------------------------------------------------------------------
# Phase 9 additions (E10 / R-03): Attention(use_scale) + MHA(use_causal_mask)
# ---------------------------------------------------------------------------

test_that("R-03: keras3 Attention(use_scale = TRUE) translates successfully", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 4L
  C_in <- 3L

  inp <- k$Input(shape = list(T_len, C_in))
  # use_scale = TRUE adds a learnable scalar multiplier on the dot-product
  # scores. R/model-keras-dotproduct-attention.R must read this weight and
  # multiply the scaled-dot-product output accordingly.
  x <- k$layers$Attention(use_scale = TRUE)(list(inp, inp))
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 8L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 2L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names

  expect_no_error(
    orb_obj <- orbital(
      model,
      mode = "regression",
      feature_names = feature_names
    )
  )
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("R-03: keras3 MultiHeadAttention with use_causal_mask = TRUE translates (static seq lengths)", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 4L
  C_in <- 8L
  num_heads <- 2L
  key_dim <- 4L

  inp <- k$Input(shape = list(T_len, C_in))
  # use_causal_mask is read from the MHA layer config by the orbital
  # translator. With static T_q / T_kv the mha-standard.R translator
  # materialises the upper-triangular mask at translation time.
  # NOTE: An earlier Wave 1A regression test above (line ~228) expected
  # use_causal_mask = TRUE to abort; that test captured the pre-remediation
  # behaviour. Phase 9 / R-03 verifies the post-remediation path.
  mha <- k$layers$MultiHeadAttention(
    num_heads = num_heads,
    key_dim = key_dim,
    use_causal_mask = TRUE
  )
  x <- mha(inp, inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  # Either the MHA layer accepts use_causal_mask as a constructor kwarg
  # (and orbital translates successfully) or it does not (and the layer
  # constructor itself aborts). We assert the translator does not abort
  # when given a valid causal-masked MHA with static shapes.
  expect_no_error(
    orb_obj <- orbital(
      model,
      mode = "regression",
      feature_names = feature_names
    )
  )
  expect_s3_class(orb_obj, "orbital")
})
