# Integration tests for keras3 / kerasnip model layers
# These tests are skipped when required packages are not installed.
# Auto-generated by _split_tests.py — do not edit the split boundary manually.

# ── B4: LSTM, GRU, Conv1D, RMSNormalization coverage tests ───────────────────

test_that("keras3 LSTM (return_sequences=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$LSTM(H, return_sequences = FALSE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 LSTM (return_sequences=TRUE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$LSTM(H, return_sequences = TRUE)(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 GRU (return_sequences=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$GRU(H, return_sequences = FALSE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 GRU (return_sequences=TRUE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$GRU(H, return_sequences = TRUE)(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, concat) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = FALSE),
    merge_mode = "concat"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(GRU, concat) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$GRU(H, return_sequences = FALSE),
    merge_mode = "concat"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, sum) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = FALSE),
    merge_mode = "sum"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, ave) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = FALSE),
    merge_mode = "ave"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, return_sequences=TRUE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 2L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = TRUE),
    merge_mode = "concat"
  )(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 SimpleRNN (return_sequences=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$SimpleRNN(H, return_sequences = FALSE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 SimpleRNN (return_sequences=TRUE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$SimpleRNN(H, return_sequences = TRUE)(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 GRU (reset_after=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$GRU(H, return_sequences = FALSE, reset_after = FALSE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_3d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

test_that("keras3 Bidirectional(LSTM, mul) predictions match keras3 predict", {
  .keras_skip()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  H <- 3L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(H, return_sequences = FALSE),
    merge_mode = "mul"
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  expect_equal(
    predict(orb_obj, df)$.pred,
    as.numeric(model$predict(x_3d, verbose = 0L)),
    tolerance = 1e-4
  )
})

test_that("keras3 stateful LSTM raises cli_abort", {
  .keras_skip()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(3L, 2L))
  x <- k$layers$LSTM(4L, stateful = TRUE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  feature_names <- paste0("x", 1:6)
  expect_error(
    orbital(model, mode = "regression", feature_names = feature_names),
    "stateful"
  )
})

test_that("keras3 stateful GRU raises cli_abort", {
  .keras_skip()
  k <- reticulate::import("keras")
  inp <- k$Input(shape = list(3L, 2L))
  x <- k$layers$GRU(4L, stateful = TRUE)(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  feature_names <- paste0("x", 1:6)
  expect_error(
    orbital(model, mode = "regression", feature_names = feature_names),
    "stateful"
  )
})

# ── ConvLSTM1D ────────────────────────────────────────────────────────────────
test_that("keras3 ConvLSTM1D (return_sequences=FALSE) predictions match keras3 predict", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  S_len <- 1L
  C_in <- 2L
  F_filt <- 4L
  inp <- k$Input(shape = list(T_len, S_len, C_in))
  x <- k$layers$ConvLSTM1D(
    filters = F_filt,
    kernel_size = 3L,
    padding = "same",
    return_sequences = FALSE
  )(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * S_len * C_in),
    nrow = n_row,
    ncol = T_len * S_len * C_in
  )
  y_vec <- rnorm(n_row)
  x_4d <- array(x_flat, dim = c(n_row, T_len, S_len, C_in))
  model$fit(x_4d, y_vec, epochs = 3L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * S_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  preds_orb <- predict(orb_obj, df)$.pred
  preds_keras <- as.numeric(model$predict(x_4d, verbose = 0L))
  expect_equal(preds_orb, preds_keras, tolerance = 1e-4)
})

# ── ConvLSTM1D error paths ────────────────────────────────────────────────────

test_that("keras3 ConvLSTM1D stateful=TRUE raises cli_abort", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  S_len <- 1L
  C_in <- 2L
  F_filt <- 4L
  inp <- k$Input(shape = list(T_len, S_len, C_in))
  x <- k$layers$ConvLSTM1D(
    filters = F_filt,
    kernel_size = 3L,
    padding = "same",
    return_sequences = FALSE,
    stateful = TRUE
  )(inp)
  x <- k$layers$Flatten()(x)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)

  feature_names <- paste0("x", seq_len(T_len * S_len * C_in))
  expect_error(
    orbital(model, mode = "regression", feature_names = feature_names),
    "stateful"
  )
})

# ── Bidirectional merge_mode=None ─────────────────────────────────────────────

test_that("keras3 Bidirectional(LSTM, merge_mode=None) falls back to concat", {
  skip_if_no_keras3()
  k <- reticulate::import("keras")
  T_len <- 3L
  C_in <- 2L
  units <- 4L
  inp <- k$Input(shape = list(T_len, C_in))
  x <- k$layers$Bidirectional(
    k$layers$LSTM(units, return_sequences = FALSE),
    merge_mode = reticulate::r_to_py(NULL)
  )(inp)
  out <- k$layers$Dense(1L)(x)
  model <- k$Model(inputs = inp, outputs = out)
  model$compile(optimizer = "adam", loss = "mse")

  set.seed(42)
  n_row <- 10L
  x_flat <- matrix(
    rnorm(n_row * T_len * C_in),
    nrow = n_row,
    ncol = T_len * C_in
  )
  x_3d <- array(x_flat, dim = c(n_row, T_len, C_in))
  model$fit(x_3d, rnorm(n_row), epochs = 2L, verbose = 0L)

  feature_names <- paste0("x", seq_len(T_len * C_in))
  df <- as.data.frame(x_flat)
  names(df) <- feature_names
  # merge_mode=None falls back to concat silently
  orb_obj <- orbital(model, mode = "regression", feature_names = feature_names)
  expect_s3_class(orb_obj, "orbital_class")
})
